import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

test('release evidence ties verified packed bytes to a clean commit and rejects dirty candidates', () => {
  const script = fileURLToPath(new URL('../scripts/release-evidence.mjs', import.meta.url));
  assert.ok(existsSync(script), 'release evidence command must exist');
  const dir = mkdtempSync(join(tmpdir(), 'waaru-release-test-'));
  writeFileSync(join(dir, 'package.json'), JSON.stringify({ name: '@waaru/sdk', version: '0.0.0-test', license: 'MIT', files: ['index.js'], scripts: { verify: 'node -e "process.exit(0)"' } }));
  writeFileSync(join(dir, 'index.js'), 'export const fixture = true;');
  writeFileSync(join(dir, 'LICENSE'), 'Fixture license for packaging test');
  const git = args => execFileSync('git', args, { cwd: dir, encoding: 'utf8', stdio: 'pipe' }).trim();
  git(['init']); git(['add', '.']);
  git(['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', '-c', 'commit.gpgsign=false', 'commit', '-m', 'fixture']);
  const run = () => spawnSync(process.execPath, [script], { cwd: dir, encoding: 'utf8' });
  const result = run();
  assert.equal(result.status, 0, result.stderr);
  const evidence = JSON.parse(result.stdout);
  assert.equal(evidence.commit, git(['rev-parse', 'HEAD']));
  assert.equal(evidence.version, '0.0.0-test');
  assert.equal(evidence.verification, 'npm run verify passed');
  assert.equal(evidence.published, false);
  assert.equal(evidence.integrity, 'sha512-' + createHash('sha512').update(readFileSync(evidence.tarballPath)).digest('base64'));
  writeFileSync(join(dir, 'index.js'), 'changed');
  assert.notEqual(run().status, 0);
  git(['add', '.']);
  assert.notEqual(run().status, 0);
  git(['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', '-c', 'commit.gpgsign=false', 'commit', '-m', 'updated fixture']);
  writeFileSync(join(dir, 'untracked.txt'), 'untracked fixture');
  assert.notEqual(run().status, 0);
  git(['add', '.']);
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  pkg.scripts.verify = 'node -e "process.exit(1)"';
  writeFileSync(join(dir, 'package.json'), JSON.stringify(pkg));
  git(['add', '.']);
  git(['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', '-c', 'commit.gpgsign=false', 'commit', '-m', 'failing verification fixture']);
  const failed = run();
  assert.notEqual(failed.status, 0);
  assert.equal(failed.stdout, '');
});
